#!/usr/bin/env php
<?php

include "src/Dates/BirthDays.php";

$birthDate = "1985-11-04";
$days = new Pskovitin\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays \n";

?>
